org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx13G -XX:+UseParallelGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableR8.fullMode=true
android.nonTransitiveRClass=true
kotlin.incremental=true

minSdkVersion=28
targetSdkVersion=28
ndkVersion=29.0.14206865
compileSdkVersion=37
